// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlG8QLblz-n7DHZBm0P6mUs7cveXctK-Q',
    appId: '1:612417036041:web:d7def7a5547b71bbaa3dd8',
    messagingSenderId: '612417036041',
    projectId: 'myfirstapp-5bde1',
    authDomain: 'myfirstapp-5bde1.firebaseapp.com',
    storageBucket: 'myfirstapp-5bde1.appspot.com',
    measurementId: 'G-XKNP0X4X1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA15wwGMFE-TDAv1vxyOgdS3MwffA1bZ70',
    appId: '1:612417036041:android:b10d2425ac662bb7aa3dd8',
    messagingSenderId: '612417036041',
    projectId: 'myfirstapp-5bde1',
    storageBucket: 'myfirstapp-5bde1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0NviKyzQRgLPvQ1_AfFkEX8RYX6AJA2I',
    appId: '1:612417036041:ios:5ebc76029b412bdeaa3dd8',
    messagingSenderId: '612417036041',
    projectId: 'myfirstapp-5bde1',
    storageBucket: 'myfirstapp-5bde1.appspot.com',
    iosClientId: '612417036041-1km79rspgfnnmdoa75oc85gvk8iao4b3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );
}
